#!/bin/sh
# anton@linevich.com, 2010
#
[ $# -eq 3 ] || { echo "Usage: $0 <iterations to store> <backuping dir> <backups destination>"; exit 13; }


set -ue
ITERATIONS=$1
DIR_TO_BACKUP=$2
PREFIX=$3


[ -d "$PREFIX/0" ] && rm -fr "$PREFIX/0"
mkdir "$PREFIX/0"

b=`basename ${DIR_TO_BACKUP}`
echo "Backuping '$DIR_TO_BACKUP'"
tar cf "$PREFIX/0/$b.tar" "$DIR_TO_BACKUP" || rm -v "$PREFIX/0/$b.tar"

DAY=$ITERATIONS
rm -fr "$PREFIX/$ITERATIONS"
while [ $DAY -ge 2  ]; do
    current_day=$DAY
    DAY=$(($DAY - 1))
    
    echo "$PREFIX/$DAY -> $PREFIX/$current_day"
    mv "$PREFIX/$DAY" "$PREFIX/$current_day" | true
done

echo "$PREFIX/ -> $PREFIX/1"
mv "$PREFIX/0" "$PREFIX/1"

