#!/bin/sh
#  Usage: aws_clodwatch_elb LB-http1 accesskey secretkey Latency

#set -x
# debug# echo "`date`: $*" >> /tmp/elb_run

source /opt/amazon/profile
set -ue

DEBUG="YES"
EPOCHTIME=$(date "+%s")

START_T=${EPOCHTIME}
END_T=$(expr ${EPOCHTIME} - 60)

#echo "$*" >> /tmp/elb_params
BALANCERNAME=$1
AWSAccessKeyId=$2
AWSSecretKey=$3
MEASURENAME=$4



# GNU VERSION, Linux machines
START_DATETIME=$(date -u --date "1970-01-01 00:00:00 ${START_T} sec" "+%FT%T")
END_DATETIME=$(date -u --date "1970-01-01 00:00:00 ${END_T} sec" "+%FT%T")

# POSIX VERSION, BSD machines
#START_DATETIME=$(date -u -r ${START_T} "+%FT%T")
#END_DATETIME=$(date -u -r ${END_T} "+%FT%T")

# --show-request --headers \
MON_OUT=$(mon-get-stats ${MEASURENAME} \
  -I ${AWSAccessKeyId} \
  -S ${AWSSecretKey} \
  --end-time ${START_DATETIME} --start-time ${END_DATETIME} \
  --period 60 \
  --show-long \
  --namespace "AWS/ELB" \
  --statistics "Average,Maximum,Minimum,Sum" \
  --dimensions "LoadBalancerName=${BALANCERNAME}" 2>&1 )


case ${MEASURENAME} in
   Latency)
   # Multiply by 1000 since values in graphs are in mseconds
   OUT=$(echo ${MON_OUT} | awk -F, '{ print "samples:"$2, "average:"$3*1000, "minimum:"$5*1000, "maximum:"$6*1000, "sum:"$4*1000 }')
   ;;
   RequestCount)
   OUT=$(echo ${MON_OUT} | awk -F, '{ print "samples:"$2/60, "average:"$3/60, "minimum:"$5/60, "maximum:"$6/60, "sum:"$4/60}')
   #OUT=$(echo ${MON_OUT} | awk -F, '{ print "samples:"$2, "average:"$3, "minimum:"$5, "maximum:"$6, "sum:"$4}')
   ;;
   UnHealthyHostCount|HealthyHostCount)
   OUT=$(echo ${MON_OUT} | awk -F, '{ print "samples:"$2, "average:"$3, "minimum:"$5, "maximum:"$6, "sum:"$4 }')
   ;;
esac

echo -n ${OUT}

#debug# echo "`date`: $OUT" >> /tmp/elb_run
[ "$DEBUG" == "YES"  ] && echo "`date`;${MEASURENAME};$MON_OUT" >>/tmp/elb_run

#Sample mon-get-stats output
# ReqestCount
#Time,Samples,Average,Sum,Minimum,Maximum,Unit
#2010-02-27 06:09:00,20367.0,1.0,20367.0,1.0,1.0,Count
#2010-02-27 06:10:00,25530.0,1.0,25530.0,1.0,1.0,Count
#Latency
#Time,Samples,Average,Sum,Minimum,Maximum,Unit
#2010-02-27 06:09:00,20367.0,0.10424164486669614,2123.089581,0.001242,19.551254,Seconds
#2010-02-27 06:10:00,25530.0,0.10715803016059537,2735.74451,0.001223,27.071693,Seconds
#2010-02-27 06:11:00,23735.0,0.09891870600379186,2347.835487,0.001203,30.802176,Seconds


