#!/bin/sh
#  Usage: aws_clodwatch_elb LB-http1 accesskey secretkey Latency

#set -x
# debug# echo "`date`: $*" >> /tmp/elb_run

[ $# -eq 5 ] || {
  echo "Usage: $0 <AccessKey> <SecretKey> <Namespace> <Dimensons> <MeasureName> "; exit 1; }

MON_GET_STATS_CMD=$(type mon-get-stats | awk '{ print $3}')
[ -x "$MON_GET_STATS_CMD" ] || source /opt/amazon/profile

set -ue

DEBUG="NO"
EPOCHTIME=$(date "+%s")

START_T=${EPOCHTIME}
# -120 secs instead of -60 because of CloudWatch delay publishing the stats
END_T=$(expr ${EPOCHTIME} - 180)

#echo "$*" >> /tmp/elb_params
AWSAccessKeyId=$1
AWSSecretKey=$2
NAMESPACE=$3
DIMENSIONS=$4
MEASURE_NAME=$5



case `uname -s` in
    Linux)
    # GNU VERSION, Linux machines
    START_DATETIME=$(date -u --date "1970-01-01 00:00:00 ${START_T} sec" "+%FT%T")
    END_DATETIME=$(date -u --date "1970-01-01 00:00:00 ${END_T} sec" "+%FT%T")
    ;;
    Darwin)
    # POSIX VERSION, BSD machines
    START_DATETIME=$(date -u -r ${START_T} "+%FT%T")
    END_DATETIME=$(date -u -r ${END_T} "+%FT%T")
    ;;
    *)
    echo "Uknown system type: `uaname -s`"
    exit 1
esac


# --show-request --headers \
#--end-time ${START_DATETIME} \

MON_OUT=$(mon-get-stats ${MEASURE_NAME} \
  -I ${AWSAccessKeyId} \
  -S ${AWSSecretKey} \
  --start-time ${END_DATETIME} \
  --period 60 \
  --show-long \
  --dimensions="$DIMENSIONS" \
  --statistics="Average,Maximum,Minimum,Sum" \
  --namespace="$NAMESPACE" )


[ "$DEBUG" == "YES"  ] && echo "`date`;${MEASURE_NAME};$MON_OUT" >>/tmp/elb_run
echo "`date`;${MEASURE_NAME};$MON_OUT" >>/tmp/elb_run


OUT=""

# AWS/RDS
case ${MEASURE_NAME} in
   CPUUtilization|DatabaseConnections|FreeStorageSpace)
   # Multiply by 1000 since values in graphs are in mseconds
   OUT=$(echo ${MON_OUT} | awk -F, '{ print "samples:"$2, "average:"$3, "minimum:"$5, "maximum:"$6, "sum:"$4 }')
   ;;
esac


# AWS/ELB
case ${MEASURE_NAME} in
   Latency)
   # Multiply by 1000 since values in graphs are in mseconds
   OUT=$(echo ${MON_OUT} | awk -F, '{ print "samples:"$2, "average:"$3*1000, "minimum:"$5*1000, "maximum:"$6*1000, "sum:"$4*1000 }')
   ;;
   RequestCount)
   OUT=$(echo ${MON_OUT} | awk -F, '{ print "samples:"$2/60, "average:"$3/60, "minimum:"$5/60, "maximum:"$6/60, "sum:"$4/60}')
   #OUT=$(echo ${MON_OUT} | awk -F, '{ print "samples:"$2, "average:"$3, "minimum:"$5, "maximum:"$6, "sum:"$4}')
   ;;
   UnHealthyHostCount|HealthyHostCount)
   OUT=$(echo ${MON_OUT} | awk -F, '{ print "samples:"$2, "average:"$3, "minimum:"$5, "maximum:"$6, "sum:"$4 }')
   ;;
esac


echo -n ${OUT}

